version: '2'
services:
    qualimaker-app:
        image: qualimaker
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://qualimaker-postgresql:5432/QualiMaker
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=qualimaker-elasticsearch:9300
        ports:
            - 8080:8080
    qualimaker-postgresql:
        extends:
            file: postgresql.yml
            service: qualimaker-postgresql
    qualimaker-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: qualimaker-elasticsearch
